### ISSUE TITLE
cbi 检查指令时不时报错

### ISSUE THREAD

**Issue by DokiOnjouji** [zyujs/clanbattle_info#11]
`[2020-11-20 13:55:59,617 nonebot] INFO: Self: 3254538608, Message -1324735317 from 137976310@[群:1056013632]: 'cbi 检查成员'
[2020-11-20 13:55:59,618 clanbattle_info] INFO: Message -1324735317 triggered cbi by PrefixTrigger.
[2020-11-20 13:56:05,092 clanbattle_info] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when cbi handling message -1324735317.
[2020-11-20 13:56:05,093 clanbattle_info] ERROR: <ActionFailed, retcode=100>
Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "/root/HoshinoBot/hoshino/modules/clanbattle_info/__init__.py", line 225, in cbi
    await bot.send(ev, msg)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 256, in send
    return await self.send_msg(**params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 223, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 161, in call_action
    return _handle_api_result(
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 51, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed: <ActionFailed, retcode=100>`

主人以外的使用倒是会正常提醒权限不足，我之前怀疑是不是主人有2个导致的，结果删除后还是报错。

**Comment by DokiOnjouji** [comment]
go-cqhttp那边提示是消息被风控，感觉不太对鸭。。。

**Comment by zyujs** [comment]
标准的长消息风控

**Comment by zyujs** [comment]
你可以尝试切换一下gocq的强制分段设置，有可能有改善

**Comment by DokiOnjouji** [comment]
噗。。可是cbi总表没报错过鸭，感觉比他长的消息的指令都没出错过
我去试试看强制分段吧

**Comment by DokiOnjouji** [comment]
草 不报错了 是不是我理解错这个分段的意思了。。。也没看出变成2段发出来的样子
