### ISSUE TITLE
开启debug模式想把前几天的数据同步到yobot内，已经切换yobot的档案，Traceback (most recent call last)

### ISSUE THREAD

**Issue by MrRumpel** [zyujs/clanbattle_info#3]
Traceback (most recent call last):
  File "/ai/HoshinoBot/hoshino/modules/clanbattle_info/__init__.py", line 204, in group_process
    await report_process(bot, group_id)
  File "/ai/HoshinoBot/hoshino/modules/clanbattle_info/yobot.py", line 379, in report_process
    ret, result = await check_yobot(group_id)
  File "/ai/HoshinoBot/hoshino/modules/clanbattle_info/yobot.py", line 346, in check_yobot
    dt = datetime.datetime.fromtimestamp(yobot_challenges[yobot_index]['challenge_time'])
IndexError: list index out of range

**Comment by MrRumpel** [comment]
Traceback (most recent call last):
  File "/ai/HoshinoBot/hoshino/modules/clanbattle_info/base.py", line 168, in load_group_config
    config = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 1 (char 451)

**Comment by MrRumpel** [comment]
关闭debug也会有这个报错，现在症状就是通过命令查询 cbi 日总表 6 数据对的，cbi boss状态 数据也对
但是cbi 状态

> 当前状态:运行中
> 
> 出刀记录推送:关闭
> 索引:0
> 
> 自动报刀:yobot嵌入模式
> 索引:0
> 状态:运行中

而且yobot内还是0条出刀记录，boss一周目状态

之前运行是正常的，索引都有值，并且推送刀的时候提示 [本条出刀记录距今已超过1天,无法上报至yobot.]

配置文件只改过 "debug": true
以及  "push_challenge": false,

**Comment by MrRumpel** [comment]
cbi 重置推送进度
cbi 重置报刀进度
这两条命令有使用过

**Comment by MrRumpel** [comment]
测试了下 "push_challenge": true,的时候

> 当前状态:运行中
> 
> 出刀记录推送:开启
> 索引:526
> 
> 自动报刀:yobot嵌入模式
> 索引:0
> 状态:运行中

yobot内依旧无数据

**Comment by MrRumpel** [comment]
手动在yobot的数据库里造了几条数据，就可以正常自动报刀了，怀疑是 空数组 导致的数组越界

**Comment by zyujs** [comment]
是的,确实是空数据造成的越界,我改一下

**Comment by MrRumpel** [comment]
Traceback (most recent call last):
  File "/ai/HoshinoBot/hoshino/modules/clanbattle_info/__init__.py", line 204, in group_process
    await report_process(bot, group_id)
  File "/ai/HoshinoBot/hoshino/modules/clanbattle_info/yobot.py", line 393, in report_process
    await bot.send_group_msg(group_id=int(group_id), message = result)

还有这里

**Comment by zyujs** [comment]
send_group_msg出错一般是因为风控发不出去消息

**Comment by MrRumpel** [comment]
对的。因为同步进度的时候反复刷屏，所以把机器人禁言了。。。
禁言机器人后，yobot里的同步也停下来了。
